config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "scenarios#index"
  get "/upload_fp_csvs", to:"dashboard#upload_fp_csvs"
  post "/submit_fp_csvs", to:"dashboard#submit_fp_csvs"

  resources :scenarios
  resources :sequential_usages, only: %i[index]
  resources :dashboard, only: %i[index]

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/report_shift.rb
class ReportShift < ApplicationRecord
  belongs_to :scenario, optional: true
end

app/models/report_total.rb
class ReportTotal < ApplicationRecord

end

app/models/scenario.rb
class Scenario < ApplicationRecord
  has_many :report_shifts

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_fp_generated_files, only: :submit_fp_csvs
  before_action :totals, only: :index
  require 'jwt'

  METABASE_SITE_URL = 'https://fleetpanda.metabaseapp.com'
  METABASE_SECRET_KEY = ENV['METABASE_SECRET_KEY']

  def index
    @scenario = Scenario.find_by(id: params[:scenario_id])
    @range = params[:date_range]
    if (chart_params["date_range"].blank? || chart_params["type"].blank? ) 
      redirect_to root_path(params: {date_range: "2021-11-01~2021-11-10", type: "NOCO2,FP3"})
    end

    payload = {
      :resource => {:dashboard => 324},
      :params => chart_params,
      :exp => Time.now.to_i + (60 * 10) # 10 minute expiration
    }
    token = JWT.encode payload, METABASE_SECRET_KEY

    @iframe_url = METABASE_SITE_URL + "/embed/dashboard/" + token + "#bordered=true&titled=false"
  end

  def upload_fp_csvs
    @available_types = ReportShift.pluck(:type).uniq.to_s
  end

  def submit_fp_csvs
    ImportShiftReportFromFpJson.new(@fp_json_files, @fp_file_type).execute
    # ImportShiftReportFromFpJson.new(@fp_json_files, @fp_file_type).routes
    redirect_back(fallback_location: root_path)
  end

  private

  def totals
    types = params[:type].split(',')
    return build_totals_variables(types) if types.size == 2

    @totals_data = {}
  end

  def build_totals_variables(types)
    @totals_data = {}
    dates = params[:date_range].split('~').map(&:to_date)
    types.each do |key|
      @totals_data[key] = {}
      values = ReportTotal.where(report_type: key, shift_date: dates[0]..dates[1]).group(:report_type)
      select_fields = []
      %w[total_hours deliveries total_volume total_miles total_time_delivery fill_rate speed
        vol_per_miles volume_per_delivery vol_per_hour_worked delivery_hour delivery_day delivery_route total_returns
      ].each do |field|
        if field == 'volume_per_delivery'
          select_fields << "sum(total_volume)/sum(NULLIF(deliveries, 0)::double precision) as #{field}"
        elsif field == 'vol_per_miles'
          select_fields << "sum(total_volume)/sum(NULLIF(total_miles, 0)::double precision) as #{field}"
        elsif field == 'vol_per_hour_worked'
          select_fields << "sum(total_volume)/sum(NULLIF(total_hours, 0)::double precision) as #{field}"
        elsif field == 'delivery_hour'
          select_fields << "sum(deliveries::double precision)/sum(NULLIF(total_hours, 0)::double precision) as #{field}"
        elsif field == 'delivery_day'
          select_fields << "sum(deliveries::double precision)/sum(NULLIF(number_days, 0)) as #{field}"
        elsif sum_field?(field)
          # @totals_data[key][field] = values.sum(field)[key]
          select_fields << "sum(#{field}) as #{field}" 
        else
          # @totals_data[key][field] = values.average(field)[key]
          select_fields << "avg(#{field}) as #{field}" 
        end
      end
      values = values.select(select_fields.join(', ')).first
      %w[total_hours deliveries total_volume total_miles total_time_delivery fill_rate speed
        vol_per_miles volume_per_delivery vol_per_hour_worked delivery_hour delivery_day delivery_route total_returns
      ].each do |field|
        @totals_data[key][field] = values.send(field)
      end
    end
    @totals_data['delta'] = {}
    %w[total_hours deliveries total_volume total_miles total_time_delivery fill_rate speed
        vol_per_miles volume_per_delivery vol_per_hour_worked delivery_hour delivery_day delivery_route total_returns
      ].each do |field|
      @totals_data['delta'][field] =
        @totals_data[types[0]][field].to_f - @totals_data[types[1]][field].to_f
    end

  end

  def sum_field?(field)
    %w[total_hours deliveries total_volume total_miles total_time_delivery total_returns].include? field
  end

  def chart_params
    {
      "date_range" => params[:date_range],
      "type" => params[:type]&.split(",")
    }
  end 


  def set_fp_generated_files 
    @fp_json_files = params[:fp_json_files][:fp_file].compact_blank
    @fp_file_type = params[:fp_json_files][:fp_file_type]
  end 

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  def index
    @scenarios = Scenario.order(:id).all
  end

  def new
    if user_signed_in?
      @scenario = Scenario.new
    else
      redirect_to :action => "index"
    end
  end

  def create
    if user_signed_in?
      @scenario = Scenario.new
      @scenario.attributes = scenario_params
      @scenario.save
    end
    redirect_to :action => "index"
  end

  def edit
    if user_signed_in?
      @scenario = Scenario.find_by(id: params[:id])
    else
      redirect_to :action => "index"
    end
  end

  def update
    if user_signed_in?
      @scenario = Scenario.find_by(id: params[:id])
      @scenario.attributes = scenario_params
      @scenario.save
    end
    redirect_to :action => "index"
  end

  def destroy
    if user_signed_in?
      @scenario = Scenario.find_by(id: params[:id])
      @scenario.destroy
    end

    redirect_to :action => "index"
  end

  def show
    @scenario = Scenario.find_by(id: params[:id])
  end

  private

  def scenario_params
    params.require(:scenario).permit(:name, :description, :link, :version, :hours_saved, :miles_saved, :files, :date)
  end 
end

app/controllers/sequential_usages_controller.rb
class SequentialUsagesController < ApplicationController

  METABASE_SITE_URL = 'https://fleetpanda.metabaseapp.com'
  METABASE_SECRET_KEY = ENV['METABASE_SECRET_KEY']

  def index
    payload = {
      :resource => {:dashboard => 333},
      :params => {},
      :exp => Time.now.to_i + (60 * 10) # 10 minute expiration
    }
    token = JWT.encode payload, METABASE_SECRET_KEY

    @iframe_url = METABASE_SITE_URL + "/embed/dashboard/" + token + "#bordered=true&titled=false"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/sequential_usages_helper.rb
module SequentialUsagesHelper
end

app/views/dashboard/index.html.erb
<style>
  .table-responsive {
    font-size: 15px;
  }
</style>
<h1>FP Customer Analysis:   <%= @range.split('~').map { |x| x.to_date.strftime('%B %d, %Y') }.join(' - ') %></h1>
<% if @scenario %>
  <h2><%=@scenario.name%><h2>
  <%= @scenario.description %>
  <br />
  <br />
<% end %>

<% if @totals_data.keys.size == 3 %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th scope="col">type</th>
        <th scope="col">Deliveries</th>
        <th scope="col">Hours*</th>
        <th scope="col">Gals</th>
        <th scope="col">Miles</th>
        <th scope="col">Time servicing</th>
        <th scope="col">Fill rate</th>
        <th scope="col">Miles/hour*</th>
        <th scope="col">Gals/miles</th>
        <th scope="col">Gals/delivery</th>
        <th scope="col">Gals/hour*</th>
        <th scope="col">Delivery/hour*</th>
        <th scope="col">Delivery/day</th>
        <th scope="col">Delivery/route</th>
        <th scope="col">Returns</th>
      </tr>
      <% @totals_data.each_key do |key| %>
        <% if key == 'delta' %>
          <tr>
            <td><%= "#{@totals_data.keys[0]} - #{@totals_data.keys[1]}" %></td>
            <td><%= number_with_precision(@totals_data[key]['deliveries'], precision: 0, delimiter: ',')%></td>
            <td class="<%= @totals_data[key]['total_hours'].negative? ? "bg-danger" : 'bg-success' %>"><%= number_with_precision(@totals_data[key]['total_hours'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_volume'], precision: 0, delimiter: ',')%></td>
            <td class="<%= @totals_data[key]['total_miles'].negative? ? "bg-danger" : 'bg-success' %>"><%= number_with_precision(@totals_data[key]['total_miles'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_time_delivery'], precision: 0, delimiter: ',')%></td>
            <td class="<%= @totals_data[key]['fill_rate'].negative? ? "bg-success" : 'bg-danger' %>"><%= number_with_precision(@totals_data[key]['fill_rate'], precision: 2, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['speed'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['vol_per_miles'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['volume_per_delivery'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['vol_per_hour_worked'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_hour'], precision: 2, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_day'], precision: 0, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_route'], precision: 0, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['total_returns'], precision: 0, delimiter: ',') %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= key %></td>
            <td><%= number_with_precision(@totals_data[key]['deliveries'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_hours'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_volume'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_miles'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['total_time_delivery'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['fill_rate'], precision: 2, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['speed'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['vol_per_miles'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['volume_per_delivery'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['vol_per_hour_worked'], precision: 0, delimiter: ',')%></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_hour'], precision: 2, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_day'], precision: 0, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['delivery_route'], precision: 0, delimiter: ',') %></td>
            <td><%= number_with_precision(@totals_data[key]['total_returns'], precision: 0, delimiter: ',') %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
<% end %>

<iframe
    src="<%= @iframe_url %>"
    frameborder="0"
    width="100%"
    height="1000"
    allowtransparency
></iframe>
<div>
  <font size="-1">*The hours do not only include travel time, it is basically shift duration, which can include other activities in addition to travel time, such as office time, lunch time, etc. On the other hand, FP hours includes only travel time and service time</font>
</div>

app/views/dashboard/upload_fp_csvs.html.erb
<h1>Upload FP generated files</h1>

<%= form_for :fp_json_files,:url=>submit_fp_csvs_path,:remote=>true,:html => { :multipart => true } do |f| %>

    <div>
        <p>Existing Data Idetifiers: <%= @available_types%></p> 
    </div>

    <div class='form-div'>
        <%= f.label :fp_file, "Select Files:", class: 'form-label'%>
        <%= f.file_field :fp_file, :required => true, multiple: true %>
    </div>
    <div class='form-div'>
        <%= f.label :fp_file_type, "Insert Data Identifier, (eg. FP2):", class: 'form-label' %>
        <%= f.text_field :fp_file_type, :required => true %>
    </div>
    <div class='form-div'>
        <%= f.button :submit ,:class=> "btn btn-go button",data: {"disable-with" => "Processing..."}%>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FpNoco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/scenarios/_form.html.erb
<h1> <%=label%> scenario</h1>
<%= form_for(@scenario) do |s| %>
  <div class="form-group">
    <div class="form-group row">
      <%= s.label :name, "Name", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.text_field :name, class: "form-control" %> 
      </div>
      <%= s.label :description, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.text_area :description, cols: 60, rows: 3, class: "form-control" %> 
      </div>
    </div>
    <div class="form-group row">
      <%= s.label :link, "Link", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.text_field :link, class: "form-control" %> 
      </div>
      <%= s.label :version, "Version", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.text_field :version, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= s.label :hours_saved, "Hours saved", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.number_field :hours_saved, step: :any, class: "form-control" %> 
      </div>
      <%= s.label :miles_saved, "Miles saved", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.number_field :miles_saved, step: :any, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= s.label :files, "Files", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.text_field :files, class: "form-control" %> 
      </div>
      <%= s.label :date, "Date", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= s.date_field :date, class: "form-control" %>
      </div>
    </div>
    <%= s.submit label, :disable_with => "Proccessing...", class: "btn btn-primary"%>
    
  </div>
<%end%>

app/views/scenarios/edit.html.erb
<%= render :partial => "form", :locals => {:label => "Update"} %>

app/views/scenarios/index.html.erb
<h1>Listing Scenarios</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Link</th>
      <th scope="col">Files</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.id %></td>
        <td><%= scenario.name %></td>
        <td><%= scenario.description %></td>
        <td><%= I18n.l scenario.date rescue '' %></td>
        <td>
          <%  if scenario.link.present? %>
            <%= link_to "Link", scenario.link %>
          <% end %>
        </td>
        <td>
          <% if scenario.files.present? %>
            <%= link_to "Files", scenario.files, target: "_blank" %>
          <% end %>
        </td>
        <% if user_signed_in? %>
          <td><%= link_to "Edit", edit_scenario_path(scenario) %></td>
          <td><%= link_to "Destroy", scenario, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
        <td><%= link_to "Details", scenario_path(scenario) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
  <%= link_to "New Scenario", new_scenario_path %>
<% end %>
<br>

<h2>Sequential route</h2>
<div>
  <%= link_to "Sequential route usage", sequential_usages_path %>
</div>

app/views/scenarios/new.html.erb
<%= render :partial => "form", :locals => {:label => "New"} %>

app/views/scenarios/show.html.erb
<div class="form-group">
  <div class="form-group row">
    <%= label_tag :name, "Name", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@scenario.name%>">
    </div>
    <%= label_tag :description, "Description", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@scenario.description%>">
    </div>
  </div>
  <div class="form-group row">
    <%= label_tag :link, "Link", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= link_to "link", @scenario.link if @scenario.link %>
    </div>
    <%= label_tag :version, "Version", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@scenario.version%>">
    </div>
  </div>

  <div class="form-group row">
    <%= label_tag :hours_saved, "Hours saved", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@scenario.hours_saved%>">
    </div>
    <%= label_tag :miles_saved, "Miles saved", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@scenario.miles_saved%>">
    </div>
  </div> 
  <div class="form-group row"> 
    <%= label_tag :files, "Files", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= link_to "Files for comparison", @scenario.files, target: "_blank" if @scenario.files %>
    </div>
  </div> 
</div>

app/views/sequential_usages/index.html.erb
<iframe
    src="<%= @iframe_url %>"
    frameborder="0"
    width="100%"
    height="1000"
    allowtransparency
></iframe>